-- STAGING STORE CREATION;

CREATE SCHEMA IF NOT EXISTS STAGING_STORE;

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_ENV_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_ENV_STAGING (
    TIME INT,
    ENERGY_CONSUMED FLOAT,  -- I
    DISTANCE FLOAT,          -- S
    LOAD_WEIGHT FLOAT,       -- L
    CO2_EMISSIONS FLOAT,     -- K
    MATERIAL_SUSTAINABILITY FLOAT, -- M
    ENV_IMPACT_SCORE FLOAT   -- Y
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_ENV_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_ENV_STAGING (
    TIME INT,
    CR_ENV FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_SAC_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_SAC_STAGING (
    TIME INT,
    POSITIVE_FEEDBACK FLOAT,  -- A
    NEGATIVE_FEEDBACK FLOAT   -- B
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_SAC_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_SAC_STAGING (
    TIME INT,
    CR_SAC FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_TFE_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_TFE_STAGING (
    TIME INT,
    CURRENT_TRL FLOAT,        -- T
    TARGET_TRL FLOAT,         -- P
    ENG_CHALLENGES_RESOLVED FLOAT, -- L
    TARGET_ENG_CHALLENGES FLOAT    -- C
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_TFE_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_TFE_STAGING (
    TIME INT,
    CR_TFE FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_SFY_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_SFY_STAGING (
    TIME INT,
    RISK_SCORE FLOAT,         -- Rn
    MIN_RISK_SCORE FLOAT,     -- MinRn
    MAX_RISK_SCORE FLOAT      -- MaxRn
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_SFY_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_SFY_STAGING (
    TIME INT,
    CR_SFY FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_REG_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_REG_STAGING (
    TIME INT,
    ETHICAL_COMPLIANCE FLOAT, -- EC
    LEGAL_COMPLIANCE FLOAT,   -- LC
    LAND_USAGE_COMPLIANCE FLOAT, -- LU
    INT_LAW_COMPLIANCE FLOAT, -- IL
    TRL_COMPLIANCE FLOAT      -- TRL
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_REG_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_REG_STAGING (
    TIME INT,
    CR_REG FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_QMF_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_QMF_STAGING (
    TIME INT,
    MAGLEV_LEVITATION BOOLEAN,
    AMBIENT_INTELLIGENCE BOOLEAN,
    GENERATIVE_AI BOOLEAN,
    AI_MACHINE_LEARNING BOOLEAN,
    DIGITAL_TWINS BOOLEAN,
    FIVE_G BOOLEAN,
    QUANTUM_COMPUTING BOOLEAN,
    AUGMENTED_REALITY BOOLEAN,
    VIRTUAL_REALITY BOOLEAN,
    PRINTING_AT_SCALE BOOLEAN,
    BLOCKCHAIN BOOLEAN,
    SELF_DRIVING_AUTONOMOUS_VEHICLES BOOLEAN,
    TOTAL_DISRUPTIVE_TECH INT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_QMF_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_QMF_STAGING (
    TIME INT,
    CR_QMF FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_ECV_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_ECV_STAGING (
    TIME INT,
    REVENUE FLOAT,             -- Rev
    OPEX FLOAT,                -- OpEx
    CAPEX FLOAT,               -- CapEx
    DISCOUNT_RATE FLOAT,       -- r
    PROJECT_LIFETIME INT       -- t
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_ECV_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_ECV_STAGING (
    TIME INT,
    CR_ECV FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_USB_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_USB_STAGING (
    TIME INT,
    PRODUCTION_OUTPUT FLOAT,   -- p
    USER_EXP_RATIO FLOAT,      -- e
    ACCESSIBILITY_AGEING FLOAT -- a
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_USB_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_USB_STAGING (
    TIME INT,
    CR_USB FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_RLB_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_RLB_STAGING (
    TIME INT,
    DURABILITY FLOAT,          -- d
    DIGITAL_RELIABILITY FLOAT, -- c
    WEATHER_DISASTER_RESILIENCE FLOAT, -- w
    POLLUTION_PRODUCED FLOAT   -- u
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_RLB_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_RLB_STAGING (
    TIME INT,
    CR_RLB FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_INF_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_INF_STAGING (
    TIME INT,
    COMMON_INFRA_FEATURES FLOAT,  -- C
    CONSTRUCTION_BARRIERS FLOAT,  -- E
    INTERMODAL_CONNECTIONS FLOAT, -- M
    INFRA_ADAPTABILITY_FEATURES FLOAT -- A
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_INF_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_INF_STAGING (
    TIME INT,
    CR_INF FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_SCL_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_SCL_STAGING (
    TIME INT,
    RESOURCE_MILEAGE FLOAT,    -- L1
    PLANNED_VOLUME FLOAT,      -- Q
    ADJUSTMENT_COEF_1 FLOAT,   -- K1
    ADJUSTMENT_COEF_2 FLOAT,   -- K2
    ADJUSTMENT_COEF_3 FLOAT    -- K3
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_SCL_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_SCL_STAGING (
    TIME INT,
    CR_SCL FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.HYPERLOOP_SPECIFICATION_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.HYPERLOOP_SPECIFICATION_STAGING (
    PARAMETER VARCHAR,
    SPECIFICATION VARCHAR
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.HYPERLOOP_ADVANCEMENTS_STAGING;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.HYPERLOOP_ADVANCEMENTS_STAGING (
    ACTUALITY VARCHAR,
    RELATED_HYPERLOOP_VENDOR VARCHAR,
    ADVANCEMENT VARCHAR
);

--
-- BACKUP TABLES SCRIPT
--

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_ENV_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_ENV_STAGING_BCK (
    TIME INT,
    ENERGY_CONSUMED FLOAT,  -- I
    DISTANCE FLOAT,          -- S
    LOAD_WEIGHT FLOAT,       -- L
    CO2_EMISSIONS FLOAT,     -- K
    MATERIAL_SUSTAINABILITY FLOAT, -- M
    ENV_IMPACT_SCORE FLOAT   -- Y
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_ENV_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_ENV_STAGING_BCK (
    TIME INT,
    CR_ENV FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_SAC_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_SAC_STAGING_BCK (
    TIME INT,
    POSITIVE_FEEDBACK FLOAT,  -- A
    NEGATIVE_FEEDBACK FLOAT   -- B
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_SAC_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_SAC_STAGING_BCK (
    TIME INT,
    CR_SAC FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_TFE_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_TFE_STAGING_BCK (
    TIME INT,
    CURRENT_TRL FLOAT,        -- T
    TARGET_TRL FLOAT,         -- P
    ENG_CHALLENGES_RESOLVED FLOAT, -- L
    TARGET_ENG_CHALLENGES FLOAT    -- C
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_TFE_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_TFE_STAGING_BCK (
    TIME INT,
    CR_TFE FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_SFY_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_SFY_STAGING_BCK (
    TIME INT,
    RISK_SCORE FLOAT,         -- Rn
    MIN_RISK_SCORE FLOAT,     -- MinRn
    MAX_RISK_SCORE FLOAT      -- MaxRn
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_SFY_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_SFY_STAGING_BCK (
    TIME INT,
    CR_SFY FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_REG_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_REG_STAGING_BCK (
    TIME INT,
    ETHICAL_COMPLIANCE FLOAT, -- EC
    LEGAL_COMPLIANCE FLOAT,   -- LC
    LAND_USAGE_COMPLIANCE FLOAT, -- LU
    INT_LAW_COMPLIANCE FLOAT, -- IL
    TRL_COMPLIANCE FLOAT      -- TRL
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_REG_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_REG_STAGING_BCK (
    TIME INT,
    CR_REG FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_QMF_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_QMF_STAGING_BCK (
    TIME INT,
    MAGLEV_LEVITATION BOOLEAN,
    AMBIENT_INTELLIGENCE BOOLEAN,
    GENERATIVE_AI BOOLEAN,
    AI_MACHINE_LEARNING BOOLEAN,
    DIGITAL_TWINS BOOLEAN,
    FIVE_G BOOLEAN,
    QUANTUM_COMPUTING BOOLEAN,
    AUGMENTED_REALITY BOOLEAN,
    VIRTUAL_REALITY BOOLEAN,
    PRINTING_AT_SCALE BOOLEAN,
    BLOCKCHAIN BOOLEAN,
    SELF_DRIVING_AUTONOMOUS_VEHICLES BOOLEAN,
    TOTAL_DISRUPTIVE_TECH INT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_QMF_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_QMF_STAGING_BCK (
    TIME INT,
    CR_QMF FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_ECV_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_ECV_STAGING_BCK (
    TIME INT,
    REVENUE FLOAT,             -- Rev
    OPEX FLOAT,                -- OpEx
    CAPEX FLOAT,               -- CapEx
    DISCOUNT_RATE FLOAT,       -- r
    PROJECT_LIFETIME INT       -- t
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_ECV_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_ECV_STAGING_BCK (
    TIME INT,
    CR_ECV FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_USB_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_USB_STAGING_BCK (
    TIME INT,
    PRODUCTION_OUTPUT FLOAT,   -- p
    USER_EXP_RATIO FLOAT,      -- e
    ACCESSIBILITY_AGEING FLOAT -- a
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_USB_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_USB_STAGING_BCK (
    TIME INT,
    CR_USB FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_RLB_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_RLB_STAGING_BCK (
    TIME INT,
    DURABILITY FLOAT,          -- d
    DIGITAL_RELIABILITY FLOAT, -- c
    WEATHER_DISASTER_RESILIENCE FLOAT, -- w
    POLLUTION_PRODUCED FLOAT   -- u
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_RLB_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_RLB_STAGING_BCK (
    TIME INT,
    CR_RLB FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_INF_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_INF_STAGING_BCK (
    TIME INT,
    COMMON_INFRA_FEATURES FLOAT,  -- C
    CONSTRUCTION_BARRIERS FLOAT,  -- E
    INTERMODAL_CONNECTIONS FLOAT, -- M
    INFRA_ADAPTABILITY_FEATURES FLOAT -- A
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_INF_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_INF_STAGING_BCK (
    TIME INT,
    CR_INF FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_SCL_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CR_SCL_STAGING_BCK (
    TIME INT,
    RESOURCE_MILEAGE FLOAT,    -- L1
    PLANNED_VOLUME FLOAT,      -- Q
    ADJUSTMENT_COEF_1 FLOAT,   -- K1
    ADJUSTMENT_COEF_2 FLOAT,   -- K2
    ADJUSTMENT_COEF_3 FLOAT    -- K3
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_SCL_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.CALC_CR_SCL_STAGING_BCK (
    TIME INT,
    CR_SCL FLOAT
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.HYPERLOOP_SPECIFICATION_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.HYPERLOOP_SPECIFICATION_STAGING_BCK (
    PARAMETER VARCHAR,
    SPECIFICATION VARCHAR
);

DROP TABLE IF EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.HYPERLOOP_ADVANCEMENTS_STAGING_BCK;
CREATE TABLE IF NOT EXISTS HPL_SYSTEM_DYNAMICS.STAGING_STORE.HYPERLOOP_ADVANCEMENTS_STAGING_BCK (
    ACTUALITY VARCHAR,
    RELATED_HYPERLOOP_VENDOR VARCHAR,
    ADVANCEMENT VARCHAR
);